name: learn-github-actions
on:
  push:
    branches:
      - production

jobs:
  push_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: git setting
      run: |
        git config --local user.email "kentaro.jay.takahashi@gmail.com"
        git config --local user.name "KentaroJay"
        git remote add heroku https://git.heroku.com/oniden-koala.git
    - name: git tests
      run: |
        git --version
        git remote -v
    - name: Deploy to Heroku
      run: |
        git push heroku production:master